CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NONE,
    password TEXT NOT NONE
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NONE,
    created TIMESTAMP NOT NONE DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NONE,
    body TEXT NOT NONE,
)
